backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img

collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "static/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Obsah aktuality", name: "body", widget: "markdown" }

  - label: "Sekce"
    name: "sections"
    files:
      - label: "Kontakt"
        name: "contact"
        file: "static/content/contact.yml"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - {label: Telefon, name: phone, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Adresa, name: address, widget: string}
      - label: "Ordinační hodiny"
        name: "opening-hours"
        file: "static/content/opening-hours.yml"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - label: Dny
            name: days
            widget: list
            fields:
              - {label: Den, name: day, widget: string}
              - {label: Dopoledne, name: morning, widget: string}
              - {label: Odpoledne, name: afternoon, widget: string}
      - label: "Ordinace"
        name: "ordination"
        file: "static/content/ordination.yml"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - {label: Popis, name: description, widget: markdown}
          - label: Služby
            name: services
            widget: list
            fields:
              - {label: Služba, name: service, widget: string}

      - label: Ceník
        name: pricing
        file: "site/content/pricing.yml"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - {label: Popis, name: description, widget: markdown}
          - label: Položky
            name: items
            widget: list
            fields:
              - {label: Název položky, name: name, widget: string}
              - {label: Cena, name: price, widget: string}
